<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0KCN5936" failures="2" tests="10" name="Test" time="0.12" errors="0" timestamp="21 Apr 2022 02:51:54 GMT">
  <testcase classname="org.pageexecution.UnknownFailures" name="test3" time="0.026"/>
  <testcase classname="org.pageexecution.UnknownFailures" name="test4" time="0.003">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="org.pageexecution.UnknownFailures" name="test4" time="0.003">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="org.pageexecution.UnknownFailures" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="org.pageexecution.UnknownFailures" name="test4" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.pageexecution.UnknownFailures.test4(UnknownFailures.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="org.pageexecution.KnownFailures" name="test1" time="0.002"/>
  <testcase classname="org.pageexecution.KnownFailures" name="test2" time="0.005">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="org.pageexecution.KnownFailures" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="org.pageexecution.KnownFailures" name="test2" time="0.005">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="org.pageexecution.KnownFailures" name="test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.pageexecution.KnownFailures.test2(KnownFailures.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
